language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libhiredis-dev libhiredis0.10 libjson0-dev libcurl4-openssl-dev check
script: sh ci.sh
rvm:
  2.0
services:
  - redis-server
branches:
  only:
    - master